// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBigkX_7HRivjNUI71ADm5MKGyFLxojaQ',
    appId: '1:726445879729:web:ce8340869837f694b9cd90',
    messagingSenderId: '726445879729',
    projectId: 'restomation-2022',
    authDomain: 'restomation-2022.firebaseapp.com',
    databaseURL: 'https://restomation-2022-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'restomation-2022.appspot.com',
    measurementId: 'G-PE0T40ZD4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfikhLCVCFP_-t-pyWk5lLLOVQPPTvmnI',
    appId: '1:726445879729:android:7d7843e8eb02d9ebb9cd90',
    messagingSenderId: '726445879729',
    projectId: 'restomation-2022',
    databaseURL: 'https://restomation-2022-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'restomation-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACKr6KMGbKjJHhnHvopecudsQ6Cu2PqR4',
    appId: '1:726445879729:ios:5eee2db43e352ec3b9cd90',
    messagingSenderId: '726445879729',
    projectId: 'restomation-2022',
    databaseURL: 'https://restomation-2022-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'restomation-2022.appspot.com',
    iosClientId: '726445879729-8p6aj8bt3rf4t6u3i5n103atlu5g2ium.apps.googleusercontent.com',
    iosBundleId: 'com.restomation.restomation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACKr6KMGbKjJHhnHvopecudsQ6Cu2PqR4',
    appId: '1:726445879729:ios:5eee2db43e352ec3b9cd90',
    messagingSenderId: '726445879729',
    projectId: 'restomation-2022',
    databaseURL: 'https://restomation-2022-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'restomation-2022.appspot.com',
    iosClientId: '726445879729-8p6aj8bt3rf4t6u3i5n103atlu5g2ium.apps.googleusercontent.com',
    iosBundleId: 'com.restomation.restomation',
  );
}
